services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.3
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
    networks:
      - default-network

  kafka:
    image: confluentinc/cp-kafka:7.5.9
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics --bootstrap-server localhost:9092 --list",
        ]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    networks:
      - default-network

  debezium:
    image: debezium/connect:2.7.3.Final
    container_name: debezium
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: "connect_configs"
      OFFSET_STORAGE_TOPIC: "connect_offsets"
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - 8083:8083
    networks:
      - default-network
  
  schema-registry:
    container_name: schema-registry
    image: confluentinc/cp-schema-registry:latest
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081, http://localhost:8081
    ports:
      - 8081:8081
    depends_on:
      - zookeeper
      - kafka
    networks:
      - default-network
  
networks:
  default-network:
    name: default-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24